<?php

namespace AppBundle\Repository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllSince(\DateTime $date){
		$query		= $this->createQueryBuilder('j')
			->where('j.dataPublicarii > :sinceDate AND j.dataPublicarii <= :today AND j.esteActiv = true')
			->setParameter('sinceDate', $date)
			->setParameter('today', new \DateTime('today'))
			->orderBy('j.dataPublicarii', 'DESC')
			->getQuery();
		
		$jobs = $query->getResult();
		return $jobs;
	}
}
