<?php

namespace AppBundle\Repository;

/**
 * OrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrasRepository extends \Doctrine\ORM\EntityRepository
{
}
